"""Approved beta data policies, shared by automation and browser disclosures."""

BACKUP_INTERVAL_HOURS = 24
BACKUP_RETENTION_DAYS = 14
RECOVERY_POINT_HOURS = 24
RECOVERY_TIME_HOURS = 2
DELETION_TARGET_HOURS = 24
OPERATOR_AUDIT_RETENTION_DAYS = 90
CLEANUP_INTERVAL_SECONDS = 60
CLEANUP_RUN_BATCH_SIZE = 25
CLEANUP_EVENT_BATCH_SIZE = 5000
CLEANUP_ACCOUNT_BATCH_SIZE = 10
CLEANUP_AUDIT_BATCH_SIZE = 1000
DELETION_QUIESCENCE_SECONDS = 60
