"""Canonical persisted-field names for followed-wallet state."""

from typing import Final

FOLLOW_STATE_VERSION_FIELD: Final = "version"
FOLLOW_WALLETS_FIELD: Final = "wallets"
FOLLOW_CONDITION_ID_FIELD: Final = "condition_id"
FOLLOW_TOKEN_ID_FIELD: Final = "token_id"
FOLLOW_MARKET_SLUG_FIELD: Final = "market_slug"
FOLLOW_SIZE_FIELD: Final = "size"
FOLLOW_BASIS_PRICE_FIELD: Final = "basis_price"
FOLLOW_OUTCOME_FIELD: Final = "outcome"
FOLLOW_SIDE_FIELD: Final = "side"
FOLLOW_PRICE_FIELD: Final = "price"
FOLLOW_TRADE_TIMESTAMP_MS_FIELD: Final = "trade_timestamp_ms"
FOLLOW_SOURCE_KEY_FIELD: Final = "source_key"
FOLLOW_EPOCH_FIELD: Final = "epoch"
FOLLOW_ACTIVE_FIELD: Final = "active"
FOLLOWED_AT_MS_FIELD: Final = "followed_at_ms"
FOLLOW_BOOTSTRAPPED_FIELD: Final = "bootstrapped"
FOLLOW_BASELINES_FIELD: Final = "baselines"
FOLLOW_MOVEMENTS_FIELD: Final = "movements"
FOLLOW_SOURCE_IDS_FIELD: Final = "source_ids"
FOLLOW_CHECKPOINT_FIELD: Final = "checkpoint"
FOLLOW_SETTLEMENTS_FIELD: Final = "settlements"
FOLLOW_EPOCH_HISTORY_FIELD: Final = "epoch_history"
FOLLOW_POSITIONS_FIELD: Final = "positions"
FOLLOW_GROSS_REALIZED_PNL_FIELD: Final = "gross_realized_pnl_usdc"
