"""Dependency-light constants for the Polymarket wallet-activity contract."""

from typing import Final

from .fields import (
    ACTIVITY_OUTCOME_FIELD,
    ACTIVITY_PRICE_FIELD,
    ACTIVITY_SIDE_FIELD,
    ACTIVITY_SIZE_FIELD,
    ACTIVITY_SLUG_FIELD,
    ACTIVITY_TITLE_FIELD,
    ACTIVITY_TIMESTAMP_FIELD,
    ACTIVITY_TOKEN_ID_FIELD,
    ACTIVITY_TRANSACTION_HASH_FIELD,
    ACTIVITY_TYPE_FIELD,
    ACTIVITY_USDC_SIZE_FIELD,
    CONDITION_ID_FIELD,
    POSITION_CASH_PNL_FIELD,
    POSITION_CURRENT_VALUE_FIELD,
    POSITION_REALIZED_PNL_FIELD,
    POSITION_SIZE_FIELD,
    PROXY_WALLET_FIELD,
    TRADE_ACTIVITY_TYPE,
)

DATA_TRADES_WINDOW_SECONDS: Final = 10
DATA_TRADES_PAGE_SIZE: Final = 499
DEFAULT_WALLET_TRADE_LIMIT: Final = 100
DEFAULT_MAX_CONCURRENCY: Final = 4
WALLET_STREAM_QUEUE_CAPACITY: Final = 1_000
WALLET_STREAM_POLL_INTERVAL_SECONDS: Final = 0.05
WALLET_STREAM_DEDUPE_CAPACITY: Final = 10_000
