"""Bounded host command and TLS observation budgets."""

HOST_COMMAND_TIMEOUT_SECONDS = 30
HTTPS_PROBE_TIMEOUT_SECONDS = 15
CERTIFICATE_WARNING_SECONDS = 7 * 24 * 3600
BACKUP_CHECK_CALENDAR = "hourly"
MONITOR_CALENDAR = "*:0/5"
