"""Bounds for advisory telemetry, independent of execution ownership."""

LIVE_PERMIT_SECONDS = 5.0
LIVE_REFRESH_SECONDS = 2.0
LIVE_REFRESH_BATCH_SIZE = 500
LIVE_INTEREST_MAX_AGE_SECONDS = 5.0
LIVE_MAX_IN_FLIGHT_PER_SHARD = 8
LIVE_MAX_SNAPSHOT_BYTES = 64 * 1024
LIVE_REDIS_POOL_SIZE = LIVE_MAX_IN_FLIGHT_PER_SHARD + 4
LIVE_CLOCK_DRIFT_SECONDS = 0.05
LIVE_CLOCK_MAX_ROUNDTRIP_SECONDS = 0.5
LIVE_CLOCK_MAX_AGE_SECONDS = LIVE_PERMIT_SECONDS
LIVE_RECONNECT_MAX_SECONDS = 2.0
LIVE_POLL_SECONDS = 0.1
LIVE_METRICS_SECONDS = 5.0
