"""Environment names, defaults, and validation sets for bot configuration."""

from decimal import Decimal
from typing import Final

from .mode import BotMode

BOT_MODE_ENV: Final = "BOT_MODE"
BOT_STREAM_RULES_ENV: Final = "BOT_STREAM_RULES"
BOT_DATA_TRADES_BUDGET_PER_10S_ENV: Final = "BOT_DATA_TRADES_BUDGET_PER_10S"
BOT_MAX_ORDER_SIZE_ENV: Final = "BOT_MAX_ORDER_SIZE"
BOT_MAX_SLIPPAGE_PCT_ENV: Final = "BOT_MAX_SLIPPAGE_PCT"
BOT_PAPER_LATENCY_MS_ENV: Final = "BOT_PAPER_LATENCY_MS"
BOT_PAPER_LATENCY_JITTER_MS_ENV: Final = "BOT_PAPER_LATENCY_JITTER_MS"
BOT_EVENT_MAX_AGE_MS_ENV: Final = "BOT_EVENT_MAX_AGE_MS"
BOT_PAPER_PORTFOLIO_USDC_ENV: Final = "BOT_PAPER_PORTFOLIO_USDC"
BOT_LIVE_ENABLED_ENV: Final = "BOT_LIVE_ENABLED"
BOT_PRIVATE_KEY_ENV: Final = "POLYMARKET_PRIVATE_KEY"
BOT_API_KEY_ENV: Final = "POLY_API_KEY"
BOT_API_SECRET_ENV: Final = "POLY_API_SECRET"
BOT_API_PASSPHRASE_ENV: Final = "POLY_API_PASSPHRASE"
BOT_FUNDER_ADDRESS_ENV: Final = "DEPOSIT_WALLET_ADDRESS"

DEFAULT_BOT_MODE: Final = BotMode.PAPER
MAX_DATA_TRADES_PER_RATE_LIMIT_WINDOW: Final = 180
DEFAULT_DATA_TRADES_BUDGET: Final = MAX_DATA_TRADES_PER_RATE_LIMIT_WINDOW
DEFAULT_MAX_ORDER_SIZE: Final = Decimal("10")
DEFAULT_MAX_SLIPPAGE_PCT: Final = Decimal("0.02")
DEFAULT_PAPER_LATENCY_MS: Final = 250
DEFAULT_PAPER_LATENCY_JITTER_MS: Final = 100
DEFAULT_EVENT_MAX_AGE_MS: Final = 5_000
DEFAULT_PAPER_PORTFOLIO_USDC: Final = Decimal("1000")
