"""Official positions API field names owned by the adapter boundary."""

from typing import Final


POSITIONS_REQUEST_USER_FIELD: Final = "user"
POSITIONS_REQUEST_SIZE_THRESHOLD_FIELD: Final = "size_threshold"
POSITIONS_REQUEST_PAGE_SIZE_FIELD: Final = "page_size"
POSITIONS_REQUEST_MARKET_FIELD: Final = "market"
POSITION_RESPONSE_WALLET_ATTRIBUTE: Final = "wallet"
POSITION_RESPONSE_TOKEN_ID_ATTRIBUTE: Final = "token_id"
POSITION_RESPONSE_CONDITION_ID_ATTRIBUTE: Final = "condition_id"
POSITION_RESPONSE_MARKET_SLUG_ATTRIBUTE: Final = "slug"
POSITION_RESPONSE_SIZE_ATTRIBUTE: Final = "size"
POSITION_RESPONSE_AVERAGE_PRICE_ATTRIBUTE: Final = "avg_price"
POSITION_RESPONSE_CURRENT_PRICE_ATTRIBUTE: Final = "cur_price"
POSITION_RESPONSE_OUTCOME_ATTRIBUTE: Final = "outcome"
