import { test, expect } from '@playwright/test';
import { AUTH_COPY } from '../src/lib/auth/copy';
import { REGISTER_PATH, LOGIN_PATH } from '../src/lib/auth/navigation';
import { NAVIGATION_PATH } from '../src/lib/navigation';
import { BOT_BUILDER_COPY } from '../src/lib/bots/copy';
import { BOT_DETAIL_COPY } from '../src/routes/bots/[botId]/copy';
import { RUN_STATUS, RUN_STATUS_PRESENTATION } from '../src/lib/runs/status';

test('private HTTPS browser login, run, Stop, refresh and stream reconnect', async ({ page }) => {
  const email = `tls-browser-${Date.now()}@example.com`;
  const password = 'disposable browser password 123';
  await page.goto(REGISTER_PATH);
  await page.getByLabel(AUTH_COPY.EMAIL, { exact: true }).fill(email);
  await page.getByLabel(AUTH_COPY.PASSWORD, { exact: true }).fill(password);
  await page.getByRole('button', { name: AUTH_COPY.REGISTER, exact: true }).click();
  await expect(page.getByRole('button', { name: AUTH_COPY.SIGN_OUT, exact: true })).toBeVisible();
  await page.getByRole('button', { name: AUTH_COPY.SIGN_OUT, exact: true }).click();
  await page.goto(LOGIN_PATH);
  await page.getByLabel(AUTH_COPY.EMAIL, { exact: true }).fill(email);
  await page.getByLabel(AUTH_COPY.PASSWORD, { exact: true }).fill(password);
  await page.getByRole('button', { name: AUTH_COPY.SIGN_IN, exact: true }).click();
  await expect(page.getByRole('button', { name: AUTH_COPY.SIGN_OUT, exact: true })).toBeVisible();
  await page.goto(NAVIGATION_PATH.NEW_BOT);
  await page.getByLabel('Name', { exact: true }).fill('HTTPS browser bot');
  await page.getByPlaceholder('Search markets by name or topic…').fill('browser');
  await page.getByRole('option').filter({ hasText: 'Will browser-market happen?' }).click();
  await page.getByRole('button', { name: BOT_BUILDER_COPY.CREATE, exact: true }).click();
  await expect(page).toHaveURL(/\/bots\/[a-f0-9-]+$/);
  await page.getByRole('button', { name: BOT_DETAIL_COPY.RUN, exact: true }).click();
  await expect(page).toHaveURL(/\/runs\/[a-f0-9-]+$/);
  const running = RUN_STATUS_PRESENTATION[RUN_STATUS.RUNNING];
  await expect(page.getByText(running.label, { exact: true }).first()).toBeVisible({ timeout: 20_000 });
  await page.reload();
  await expect(page.getByText(running.label, { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: running.stopLabel!, exact: true }).click();
  const stopped = RUN_STATUS_PRESENTATION[RUN_STATUS.STOPPED];
  await expect(page.getByText(stopped.label, { exact: true }).first()).toBeVisible({ timeout: 20_000 });
  await page.reload();
  await expect(page.getByText(stopped.label, { exact: true }).first()).toBeVisible();
});
