"""Wallet timeline and copied-order identities survive real PostgreSQL JSONB."""

import asyncio
import os
from datetime import UTC, datetime
from decimal import Decimal
from uuid import uuid4

import pytest
from api.auth.models import UserRow  # noqa: F401 - register referenced ORM metadata
from api.bots.models import BotRow  # noqa: F401 - register referenced ORM metadata
from api.database import async_database_url
from api.events.contracts import (
    BrokerFillEvent,
    BrokerFillPayload,
    BrokerOrderEvent,
    BrokerOrderPayload,
)
from api.events.ids import FIRST_EVENT_CURSOR
from api.events.projection import project_runtime_event_to_durable
from api.events.schema import RUN_EVENTS_TABLE_NAME, EventColumn
from api.events.store import EventStore
from api.runs.models import RunRow  # noqa: F401 - register referenced ORM metadata
from polybot.cli.observability.events import DispatchCompleted
from polybot.cli.streams.contracts import WalletStreamEvent
from polybot.cli.streams.kinds import StreamKind
from polybot.examples.wallet_copy import FixedDollarCopyPolicy
from polybot.framework.dispatch import DispatchOutcome
from polybot.framework.events import FillEvent, OrderStatus, Side
from polybot.framework.events.wallet_trades import (
    WALLET_SOURCE_KEY_SEPARATOR,
    WalletTradeEvent,
)
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine

from control_plane.service_config import (
    POSTGRES_NOT_CONFIGURED_SKIP_REASON,
    TEST_POSTGRES_URL_ENV,
)


@pytest.mark.postgres
def test_wallet_timeline_and_copy_fill_persist_source_identity() -> None:
    url = os.getenv(TEST_POSTGRES_URL_ENV)
    if not url:
        pytest.skip(POSTGRES_NOT_CONFIGURED_SKIP_REASON)

    async def scenario():
        engine = create_async_engine(async_database_url(url))
        try:
            async with engine.connect() as connection:
                await connection.execute(
                    text(
                        f"CREATE TEMP TABLE {RUN_EVENTS_TABLE_NAME} ("
                        f"{EventColumn.ID} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        f"{EventColumn.RUN_ID} UUID, {EventColumn.KIND} TEXT, "
                        f"{EventColumn.OCCURRED_AT} TIMESTAMPTZ, {EventColumn.PAYLOAD} JSONB)"
                    )
                )
                await connection.commit()
                async with AsyncSession(connection) as session:
                    store = EventStore(session)
                    run_id = uuid4()
                    trade = WalletTradeEvent(
                        wallet="0x" + "a" * 40,
                        condition_id="condition",
                        token_id="token",
                        side=Side.BUY,
                        size=Decimal("2"),
                        price=Decimal("0.5"),
                        source_id=f"transaction{WALLET_SOURCE_KEY_SEPARATOR}index",
                        trade_timestamp_ms=1,
                        observed_at_ms=1,
                        market_slug="market",
                    )
                    (timeline,) = project_runtime_event_to_durable(
                        run_id,
                        DispatchCompleted(
                            WalletStreamEvent(StreamKind.WALLET, trade),
                            DispatchOutcome.accepted_event(),
                            1.0,
                        ),
                    )
                    order = FixedDollarCopyPolicy.order(trade)
                    fill = FillEvent(
                        order_id="order",
                        token_id=trade.token_id,
                        side=order.side,
                        status=OrderStatus.FILLED,
                        requested_size=order.size,
                        filled_size=order.size,
                        average_price=order.price,
                        fee_usdc=Decimal("0"),
                        received_at_ms=1,
                    )
                    now = datetime.now(UTC)
                    events = (
                        timeline,
                        BrokerOrderEvent(
                            run_id=run_id,
                            occurred_at=now,
                            payload=BrokerOrderPayload(order=order),
                        ),
                        BrokerFillEvent(
                            run_id=run_id,
                            occurred_at=now,
                            payload=BrokerFillPayload(
                                order=order, fill=fill, portfolio=None, latency_ms=0
                            ),
                        ),
                    )
                    persisted = tuple([await store.append(event) for event in events])
                    assert (
                        await store.read(run_id, after_event_id=FIRST_EVENT_CURSOR)
                        == persisted
                    )
                    assert persisted[0].payload.point.source_key == trade.source_key
                    assert persisted[1].payload.order.source_id == trade.source_key
                    assert persisted[2].payload.order.source_id == trade.source_key
        finally:
            await engine.dispose()

    asyncio.run(scenario())
