"""Persisted field names and schema versions for resolution ledgers."""

from typing import Final

from polybot.framework.events.resolution_fields import (
    RESOLUTION_RESOLVED_AT_MS_FIELD,
    RESOLUTION_SETTLED_AT_MS_FIELD,
    RESOLUTION_SOURCE_FIELD,
    RESOLUTION_WINNING_OUTCOME_FIELD,
    RESOLUTION_WINNING_TOKEN_ID_FIELD,
)


RESOLUTION_LEDGER_VERSION: Final = 1
RESOLUTION_LEDGER_VERSION_FIELD: Final = "version"
RESOLUTION_RECORDS_FIELD: Final = "resolutions"
RESOLUTION_LEDGER_FIELDS = frozenset(
    {RESOLUTION_LEDGER_VERSION_FIELD, RESOLUTION_RECORDS_FIELD}
)
RESOLUTION_RECORD_FIELDS = frozenset(
    {
        RESOLUTION_WINNING_TOKEN_ID_FIELD,
        RESOLUTION_WINNING_OUTCOME_FIELD,
        RESOLUTION_RESOLVED_AT_MS_FIELD,
        RESOLUTION_SETTLED_AT_MS_FIELD,
        RESOLUTION_SOURCE_FIELD,
    }
)
