"""Runtime environment names and listener defaults shared by deployment adapters."""

BUNDLE_DIRECTORY_ENV = "POLYBOT_BUNDLE_DIRECTORY"
HTTP_PORT_MINIMUM = 1024
HTTP_PORT_MAXIMUM = 65535
HTTP_PORT_ENV = "POLYBOT_HTTP_PORT"
SECRETS_DIRECTORY_ENV = "POLYBOT_SECRETS_DIR"
DEFAULT_HTTP_PORT = 8081
DEFAULT_AUTH_ORIGIN = "https://localhost:8443"
DEFAULT_SMTP_PORT = 587
